const UserActionTypes = {
  FETCH_USER: "FETCH_USER",
  SIGNUP_USER: "SIGNUP_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  LOGIN_GOOGLE: "LOGIN_GOOGLE",
  SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
};

export default UserActionTypes;
